---
title: "Untitled"
output: html_document
date: "2024-06-28"
---

```{r}
library(tidyverse)
library(rvest)
```

Grab election results from MD DEPT OF ELECTIONS pages
```{r}
# Start by reading a HTML page with read_html():
results <- read_html("https://elections.maryland.gov/elections/2024/Primary_Results/gen_results_2024_1.html")


#FIRST SCRAPE DEM RESULTS

# find elements that match a css selector or XPath expression
dem_candidates <- results %>% 
  html_nodes(xpath='//*[@id="primary_right_col"]/div/div[8]/table') %>%
  html_table()


#convert the tibble returned above to a data frame
dem_candidates <- as.data.frame(dem_candidates)

# remove the commas from the column total
dem_candidates$Total <- gsub(',', '', dem_candidates$Total)


#write to csv
#write.csv(dem_candidates,"dem_candidates.csv", row.names = FALSE) 



# NEXT SCRAPE REPUBLICAN RESULTS

# Find elements that match a css selector or XPath expression
rep_candidates <- results %>% 
  html_nodes(xpath='//*[@id="primary_right_col"]/div/div[10]/table') %>%
  html_table()

#convert the tibble returned above to a data frame
rep_candidates <- as.data.frame(rep_candidates)

# remove the commas from the column total
rep_candidates$Total <- gsub(',', '', rep_candidates$Total)

#write to csv
#write.csv(rep_candidates,"rep_candidates.csv", row.names = FALSE) 

```


Grab results from my test page (testing the entire workflow)
```{r}
# Start by reading a HTML page with read_html():
test_results <- read_html("https://amarton.github.io/your-name-jour352/test-table.html")

# find elements that match a css selector or XPath expression
test_candidates <- test_results %>% 
  html_nodes(xpath='/html/body/table') %>%
  html_table()

#convert the tibble returned above to a data frame
test_candidates <- as.data.frame(test_candidates)


# remove the commas from the column votes
test_candidates$Total <- gsub(',', '', test_candidates$Total)

#this will delete the final row from the dataframe
  #Change to -2 to delete 2 rows
test_candidates <- test_candidates %>% filter(row_number() <= n()-1)


#write to csv
#write.csv(test_candidates,"test_candidates.csv", row.names = FALSE) 

```


Grab election results from MD DEPT OF ELECTIONS pages
```{r}
# Start by reading a HTML page with read_html():
#presidential election
pres_results <- read_html("https://elections.maryland.gov/elections/2020/results/general/gen_results_2020_4_001-.html")

#house reps
reps_results <- read_html("https://elections.maryland.gov/elections/2020/results/general/gen_results_2020_4_008X.html")

#question 1
question1_results <- read_html("https://elections.maryland.gov/elections/2020/results/general/gen_qresults_2020_4_00_1.html")

#senate
sen_results <- read_html("https://elections.maryland.gov/elections/2022/general_results/gen_results_2022_4.html")


#SCRAPE REPS RESULTS
#let's loop these!!

# find elements that match a css selector or XPath expression
reps_d1 <- reps_results %>% 
  html_nodes(xpath='//*[@id="primary_right_col"]/div/div[3]/table') %>%
  html_table()

#convert the tibble returned above to a data frame
reps_d1 <- as.data.frame(reps_d1)

# remove the commas from the column total
reps_d1$Total <- gsub(',', '', reps_d1$Total)

# find elements that match a css selector or XPath expression
reps_d2 <- reps_results %>% 
  html_nodes(xpath='//*[@id="primary_right_col"]/div/div[5]/table') %>%
  html_table()

#convert the tibble returned above to a data frame
reps_d2 <- as.data.frame(reps_d2)

# remove the commas from the column total
reps_d2$Total <- gsub(',', '', reps_d2$Total)

#write to csv
#write.csv(dem_candidates,"dem_candidates.csv", row.names = FALSE) 
#DO WE NEED TO SHOW ALL THESE CANDIDATES?

#SCRAPE PRES RESULTS

# find elements that match a css selector or XPath expression
pres_candidates <- pres_results %>% 
  html_nodes(xpath='//*[@id="primary_right_col"]/div/div[3]/table') %>%
  html_table()

#convert the tibble returned above to a data frame
pres_candidates <- as.data.frame(pres_candidates )

# remove the commas from the column total
pres_candidates$Total <- gsub(',', '', pres_candidates$Total)


#write to csv
#write.csv(dem_candidates,"dem_candidates.csv", row.names = FALSE) 
#DO WE NEED TO SHOW ALL THESE CANDIDATES?

]

```


