name: election scraper r

on:
  schedule:
    - cron: "0 8 * * *"  # 8 a.m. every day UTC
  push:
    branches: main

jobs:
  render:
    name: Scrape R test
    runs-on: macOS-latest  # Keep macOS if you need it, but switch to ubuntu-latest if no specific macOS requirements

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2  # Consider upgrading to v3 if available

      # Install Pandoc
      - name: Install Pandoc
        run: |
          brew install pandoc  # macOS specific; brew is the package manager
          pandoc --version      # Optional: Check installed version

      # Install necessary R packages
      - name: Install dependencies
        run: Rscript -e "install.packages(c('rmarkdown', 'tidyverse', 'rvest', 'dplyr', 'lubridate'))"

      # Render the R Markdown file
      - name: Scrape the data from R markdown
        run: Rscript -e "rmarkdown::render('election_scraper_2024.rmd')"

      # Add and commit any changes
      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v8
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest data"
